services:
  - type: web
    name: poke-tegus
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: TEGUS_EMAIL
        sync: false
      - key: TEGUS_PASSWORD
        sync: false
